#!/bin/sh

bg_color=#ff2f343f
text_color=#fff3f4f5
htext_color=#ff9575cd


rofi -show run -lines 5 -eh 2 -width 100 -padding 1000 -bw 0 -color-window "$bg_color, $bg_color, $bg_color" -color-normal "$bg_color, $text_color, $bg_color, $bg_color, $htext_color" -font "System San Francisco Display 16"
